### ISSUE TITLE
can not fetch countries from commerce.js 

### ISSUE THREAD

**Issue by sayanmondal31** [adrianhajdin/project_e_commerce#10]
Everything is working but when comes to fetching list of shipping countries, can't fetch that but the checkoutTokenID is showing properly.

**Comment by noorfaiqah** [comment]
Have you enabled shipping for each product?

**Comment by sayanmondal31** [comment]
Thank you @noorfaiqah. I **opened every product item** to the commerce.js dashboard and **enabled shipping options** and **save it**. and then **re-run my site** and it works.
