### ISSUE TITLE
Anybody faced this and what's the solution? After clicking Checkout it's displaying white blank screen.

### ISSUE THREAD

**Issue by koushik80** [adrianhajdin/project_e_commerce#46]
## react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

**Comment by kabir0x17** [comment]
> ## Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> ## The above error occurred in the
> component:
> ## react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

are you on addressForm or on checkout section

**Comment by rjmead23** [comment]
Can you post your code from the Checkout.jsx file here? It will make looking into your issue easier.
